(function(){
  "use strict";
  const JOBS_KEY="nosmo-work:jobs/v1";
  const APPS_KEY="nosmo-work:applications/v1";
  const EMPLOYERS_KEY="nosmo-work:employers/v1";
  const CONTACT_LOG_KEY="nosmo-work:application-log/v1";
  const DEMO_MODE=new URLSearchParams(location.search).get("demo")==="1"||localStorage.getItem("nosmo-work:demo/v1")==="true";
  const STATUSES=["NEW","TO APPLY","APPLIED","REPLY","INTERVIEW","OFFER","REJECTED","CLOSED"];
  const CONSTRUCTION_TRADES=["General labourer","Site operative","Carpenter / Joiner","Dryliner","Painter / Decorator","Bricklayer","Plasterer","Electrician","Plumber","Heating engineer","Roofer","Groundworker","Concrete finisher","Steel fixer","Scaffolder","Tiler","Floor layer","Plant operator","Telehandler operator","Crane operator","Banksman / Traffic marshal","Fire stopper","Snagging / Finishing","Site supervisor","Site manager","Quantity surveyor","Setting-out engineer","Document controller","Health and safety"];
  const CONSTRUCTION_TERMS=["construction","site ","site-","building","builder","labour","operative","carpenter","joiner","drylin","ceiling fixer","painter","decorator","brick","mason","plaster","render","electric","ecs","plumb","pipefitter","heating","roofer","roofing","groundwork","drainage","concrete","steel fixer","scaffold","tiler","floor layer","plant operator","telehandler","excavator","dumper","crane","banksman","traffic marshal","fire stop","firestop","snagging","finishing","supervisor","manager","quantity surveyor","setting out","document controller","health and safety","h&s","m&e"];
  const demoJobs=[
    {id:"demo-job-1",role:"Carpenter / Joiner",company:"NorthBuild Recruitment",location:"Leeds",distance:"4 mi",travelTime:"18 min",rate:"£22–£24/hour",hours:"07:30–16:30",employmentType:"CIS / Contract",source:"Demo employer record",sourceUrl:"",phone:"+44 7700 900111",email:"jobs@example.invalid",whatsapp:true,status:"NEW",localDemo:true},
    {id:"demo-job-2",role:"Multi-skilled Operative",company:"West Yorkshire Trades",location:"Bradford",distance:"7 mi",travelTime:"26 min",rate:"£19/hour",hours:"Day shift",employmentType:"Temporary / Agency",source:"Demo agency record",sourceUrl:"",phone:"",email:"recruitment@example.invalid",whatsapp:false,status:"TO APPLY",localDemo:true}
  ];
  const demoEmployers=[
    {id:"demo-employer-1",company:"NorthBuild Recruitment",location:"Leeds",contactName:"Recruiter placeholder",phone:"+44 7700 900111",email:"jobs@example.invalid",whatsapp:"Known",website:"",source:"Demo employer record",notes:"Local/demo contact only.",status:"PROSPECT",localDemo:true},
    {id:"demo-employer-2",company:"West Yorkshire Trades",location:"Bradford",contactName:"",phone:"",email:"recruitment@example.invalid",whatsapp:"Unknown",website:"",source:"Demo agency record",notes:"Local/demo contact only.",status:"CONTACT READY",localDemo:true}
  ];
  const q=s=>document.querySelector(s);
  const qa=s=>Array.from(document.querySelectorAll(s));
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function read(key,fallback=[]){try{const v=JSON.parse(localStorage.getItem(key)||"null");return Array.isArray(v)?v:fallback}catch(_){return fallback}}
  function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
  function constructionTrade(value){const text=String(value||"").toLowerCase();return CONSTRUCTION_TRADES.find(trade=>trade.toLowerCase().split(/\s+|\//).some(token=>token.length>3&&text.includes(token)))||"Other construction"}
  function isConstructionJob(job){if(job?.constructionOnly===true)return true;const text=[job?.role,job?.title,job?.category,job?.sector,job?.industry,job?.description].join(" ").toLowerCase();return CONSTRUCTION_TERMS.some(term=>text.includes(term))}
  function normalizeJob(j){const role=j.role||j.title||"Construction job";return {id:j.id||j.externalId||("gateway-"+Date.now()),role,trade:j.trade||constructionTrade(role),constructionOnly:j.constructionOnly===true||isConstructionJob(j),company:j.company||j.employer||"Employer",location:j.location||"",distance:j.distance||((j.distanceKm??"")!==""?j.distanceKm+" km":""),travelTime:j.travelTime||"",rate:j.rate||"Not stated",hours:j.hours||j.shift||"Not stated",employmentType:j.employmentType||"Not stated",source:j.source||j.sourceId||j.provider||"Job Gateway",sourceUrl:j.sourceUrl||j.redirectUrl||j.url||"",phone:j.phone||"",email:j.email||"",whatsapp:!!j.whatsapp,status:j.status||"NEW",matchScore:j.matchScore,reasons:j.reasons||[],gaps:j.gaps||[],localDemo:j.sourceMode==="synthetic"}}
  function normalizeEmployer(e){return {id:e.id||("agency-"+Date.now()),company:e.company||e.name||"Agency",location:e.location||"",contactName:e.contactName||e.desk||"",phone:e.phone||"",email:String(e.email||"").replace(/^mailto:/,"").split("?")[0],whatsapp:e.whatsapp?"Known":"Unknown",website:e.website||"",source:e.source||"Canonical Work Profile",notes:e.notes||"",status:String(e.status||"PROSPECT").toUpperCase(),localDemo:e.status==="demo"}}
  function jobs(){const canonical=(window.NEXUS_WORK_PROFILE?.jobMatches||[]).map(normalizeJob).filter(isConstructionJob),local=read(JOBS_KEY).map(normalizeJob).filter(isConstructionJob),appStatus=new Map(applications().map(a=>[a.jobId,a.status]));const base=canonical.length?canonical:(DEMO_MODE?demoJobs.map(normalizeJob):[]);return [...base,...local].map(job=>({...job,status:appStatus.get(job.id)||job.status}))}
  function employers(){const canonical=(window.NEXUS_WORK_PROFILE?.agencies||[]).map(normalizeEmployer);const base=canonical.length?canonical:(DEMO_MODE?demoEmployers:[]);return [...base,...read(EMPLOYERS_KEY)]}
  function applications(){return read(APPS_KEY)}
  function canonicalCard(){return typeof loadWorkCard==="function"?loadWorkCard():{profile:{},skills:[],licences:[]}}
  function documents(){return typeof allDocuments==="function"?allDocuments():[]}
  function currentCv(){const registered=read("nosmo-work:file-registry/v1").find(f=>f.fileRole==="cv");if(registered)return {name:registered.name||registered.fileName||"CV",source:"Documents local file registry",fileId:registered.id};return documents().find(d=>d.type==="cv"&&!d.placeholder)||null}
  function availability(card){
    const value=card.profile?.availability||"Not available";
    return value==="Available from date"&&card.profile.availableFrom?"Available from "+card.profile.availableFrom:value;
  }
  function score(job,card){
    const text=[job.role,job.company,job.location,job.employmentType].join(" ").toLowerCase();
    const tokens=[card.profile?.currentRole,...(card.skills||[]).map(s=>s.name)].join(" ").toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3);
    const hits=[...new Set(tokens.filter(t=>text.includes(t)))];
    let value=48+Math.min(30,hits.length*9);const reasons=[];const gaps=[];
    if(hits.length)reasons.push("Role / skills: "+hits.slice(0,3).join(", "));
    const location=String(card.profile?.preferredLocation||"").toLowerCase();
    if(location&&location.split(/[\/;,]/).some(x=>x.trim()&&String(job.location).toLowerCase().includes(x.trim()))){value+=14;reasons.push("Preferred location")}
    if(!currentCv())gaps.push("CV missing in Documents");
    if(!(card.licences||[]).length)gaps.push("No licences / tickets recorded");
    if(!reasons.length)reasons.push("General Work Profile relevance");
    if(Number.isFinite(job.matchScore))value=job.matchScore;if(job.reasons?.length)reasons.splice(0,reasons.length,...job.reasons);if(job.gaps?.length)gaps.splice(0,gaps.length,...job.gaps,...gaps);
    return {value:Math.min(98,value),reasons,gaps};
  }
  function setTab(tab){qa("[data-hub-tab]").forEach(b=>b.classList.toggle("active",b.dataset.hubTab===tab));qa("[data-hub-panel]").forEach(p=>p.hidden=p.dataset.hubPanel!==tab);if(tab==="jobs")renderJobs();if(tab==="applications")renderApplications();if(tab==="employers")renderEmployers()}
  function context(){const card=canonicalCard(),cv=currentCv();q("#workAgentContext").innerHTML='<b>Canonical context:</b> '+esc(card.profile?.currentRole||"role not set")+' · '+esc(availability(card))+' · '+esc(card.profile?.preferredLocation||"location not set")+' · '+esc((card.skills||[]).length)+' skills · '+esc((card.licences||[]).length)+' tickets<br>'+(cv?'Selected CV: <b>'+esc(cv.name)+'</b> (reference from Documents)':'<b>No CV available.</b> <a href="./screen.html?screen=documents">Add CV in Documents</a>');}
  function statusOptions(value){return STATUSES.map(s=>'<option '+(s===value?'selected':'')+'>'+s+'</option>').join("")}
  function renderJobs(){
    context();const card=canonicalCard(),term=(q("#jobSearchInput")?.value||"").toLowerCase(),filter=q("#jobStatusFilter")?.value||"",trade=q("#constructionTradeFilter")?.value||"";
    const list=jobs().map(j=>({...j,_score:score(j,card)})).filter(j=>(!term||[j.role,j.company,j.location,j.source].join(" ").toLowerCase().includes(term))&&(!filter||j.status===filter)&&(!trade||j.trade===trade)).sort((a,b)=>b._score.value-a._score.value);
    q("#jobHubList").innerHTML=list.length?list.map(j=>'<article class="hubCard"><div class="hubCardTop"><div><h3>'+esc(j.role)+'</h3><div class="hubCompany">'+esc(j.company)+'</div></div><div class="hubMatch">'+j._score.value+'%</div></div><div class="hubMeta"><span>'+esc(j.location)+'</span><span>'+esc(j.distance||"Distance n/a")+' · '+esc(j.travelTime||"Time n/a")+'</span><span>'+esc(j.rate||"Rate n/a")+'</span><span>'+esc(j.hours||"Hours n/a")+'</span><span>'+esc(j.employmentType||"Type n/a")+'</span><span>'+esc(j.status)+'</span><span>'+esc(j.source)+'</span></div><p class="hubReason"><b>Why matched:</b> '+esc(j._score.reasons.join(" · "))+'</p>'+(j._score.gaps.length?'<p class="hubReason"><b>Check:</b> '+esc(j._score.gaps.join(" · "))+'</p>':'')+'<div class="hubActions"><button class="apply" type="button" data-prepare="'+esc(j.id)+'">Prepare application</button><button type="button" data-job-detail="'+esc(j.id)+'">Full record</button>'+(j.sourceUrl?'<a href="'+esc(j.sourceUrl)+'" target="_blank" rel="noopener">Original source / Open page</a>':'')+'</div></article>').join(""):'<div class="empty">No jobs saved or found yet. Add a job or connect a live job source.</div>';
  }
  function openSheet(title,html){q("#workHubSheetTitle").textContent=title;q("#workHubSheetBody").innerHTML=html;q("#workHubBackdrop").classList.add("open");q("#workHubBackdrop").setAttribute("aria-hidden","false")}
  function closeSheet(){q("#workHubBackdrop").classList.remove("open");q("#workHubBackdrop").setAttribute("aria-hidden","true")}
  function applicationDraft(job){const c=canonicalCard();return "Hi "+job.company+",\n\nI would like to apply for the "+job.role+" role in "+job.location+". My canonical NOSMO Work Card lists my role as "+(c.profile.currentRole||"not yet set")+" and my availability as "+availability(c)+".\n\nPlease let me know what verified information or documents you require. I will review and share them myself.\n\nKind regards"}
  function prepare(job){const cv=currentCv(),draft=applicationDraft(job),rows=applications(),now=new Date().toISOString();let application=rows.find(a=>a.jobId===job.id);if(!application){application={id:"app-"+Date.now(),jobId:job.id,status:"TO APPLY",nextAction:"Review draft and apply",followUp:"",createdAt:now,updatedAt:now,draft,selectedCvRef:cv?{name:cv.name,fileId:cv.fileId||null,source:"Documents"}:null,history:[{status:"TO APPLY",at:now,source:"draft-prepared-locally"}]};rows.unshift(application)}else{application.draft=draft;application.selectedCvRef=cv?{name:cv.name,fileId:cv.fileId||null,source:"Documents"}:null;application.updatedAt=now}write(APPS_KEY,rows);const engine=window.NEXUS_CONTACT_ACTION_ENGINE;engine?.setJob?.({id:job.id,title:job.role,employer:job.company,contact:{phone:job.phone,email:job.email,whatsapp:job.phone}});openSheet("Application draft",'<div class="detail"><div class="detailRow"><span>Role</span><strong>'+esc(job.role)+' · '+esc(job.company)+'</strong></div><div class="cvRef">'+(cv?'Selected CV: <b>'+esc(cv.name)+'</b> — reference from Documents. It is not attached automatically.':'<b>No CV.</b> <a href="./screen.html?screen=documents">Add CV in Documents</a>')+'</div><label class="hubForm"><span>Review draft</span><textarea id="hubDraft">'+esc(application.draft||draft)+'</textarea></label><div class="hubActions">'+(job.whatsapp&&job.phone?'<a id="hubWhatsApp" href="https://wa.me/'+esc(job.phone.replace(/\D/g,""))+'?text='+encodeURIComponent(draft)+'" target="_blank" rel="noopener">Open WhatsApp</a>':'')+(job.email?'<a id="hubEmail" href="mailto:'+esc(job.email)+'?subject='+encodeURIComponent('Application — '+job.role)+'&body='+encodeURIComponent(draft)+'">Open email</a>':'')+'<button class="apply" id="confirmApplicationSent" type="button">I SENT IT</button></div><p class="localOnly">Draft preparation records TO APPLY only. Opening a channel never counts as sent. Only I SENT IT records your explicit confirmation. No CV or private document is uploaded by NOSMO.</p></div>');q("#hubWhatsApp")?.addEventListener("click",()=>engine?.recordOpened?.({id:job.id,title:job.role,employer:job.company},"whatsapp"));q("#hubEmail")?.addEventListener("click",()=>engine?.recordOpened?.({id:job.id,title:job.role,employer:job.company},"email"));q("#confirmApplicationSent")?.addEventListener("click",()=>confirmSent(job));renderJobs()}
  function confirmSent(job){if(!window.confirm("Confirm that you personally sent this application?"))return;const rows=applications();const now=new Date().toISOString();const existing=rows.find(x=>x.jobId===job.id);if(existing){existing.status="APPLIED";existing.updatedAt=now;existing.history.push({status:"APPLIED",at:now,source:"explicit-user-confirmation"})}else rows.unshift({id:"app-"+Date.now(),jobId:job.id,status:"APPLIED",nextAction:"Follow up with employer",followUp:"",createdAt:now,updatedAt:now,history:[{status:"APPLIED",at:now,source:"explicit-user-confirmation"}]});write(APPS_KEY,rows);const engine=window.NEXUS_CONTACT_ACTION_ENGINE;if(engine?.confirmSent)engine.confirmSent({id:job.id,title:job.role,employer:job.company},{explicitUserConfirmation:true});else{const log=read(CONTACT_LOG_KEY);log.unshift({schema:"nexus-contact-action-event/v1",status:"sent-confirmed",jobId:job.id,jobTitle:job.role,employer:job.company,at:now,serverTransmissionPerformed:false,explicitUserConfirmation:true});write(CONTACT_LOG_KEY,log)}closeSheet();showWorkToast("Application recorded only from your confirmation.")}
  function renderApplications(){const rows=applications(),all=jobs();q("#applicationsSent").textContent=rows.filter(x=>x.history?.some(h=>h.status==="APPLIED")).length;q("#repliesToCheck").textContent=rows.filter(x=>["REPLY","INTERVIEW","OFFER"].includes(x.status)).length;q("#needsAction").textContent=rows.filter(x=>x.nextAction&&!["REJECTED","CLOSED"].includes(x.status)).length;q("#attentionCopy").textContent=rows.find(x=>x.nextAction)?.nextAction||"No confirmed follow-up is due.";q("#applicationHubList").innerHTML=rows.length?rows.map(a=>{const j=all.find(x=>x.id===a.jobId)||{role:"Job record",company:"Employer",location:""};return '<article class="hubCard"><div class="hubCardTop"><div><h3>'+esc(j.role)+'</h3><div class="hubCompany">'+esc(j.company)+' · '+esc(j.location)+'</div></div><span class="hubStatus '+esc(a.status.toLowerCase())+'">'+esc(a.status)+'</span></div><div class="hubMeta"><span>Next: '+esc(a.nextAction||"None")+'</span><span>Follow-up: '+esc(a.followUp||"Not scheduled")+'</span></div><div class="hubActions"><button data-app-detail="'+esc(a.id)+'">Open full record</button></div></article>'}).join(""):'<div class="empty">No applications recorded. Opening WhatsApp, email or a job page does not create a sent application.</div>'}
  function renderEmployers(){const term=(q("#employerSearchInput")?.value||"").toLowerCase(),apps=applications(),allJobs=jobs();const list=employers().filter(e=>!term||[e.company,e.location,e.contactName,e.notes].join(" ").toLowerCase().includes(term));q("#employerHubList").innerHTML=list.length?list.map(e=>{const history=apps.filter(a=>allJobs.find(j=>j.id===a.jobId)?.company===e.company);return '<article class="hubCard"><div class="hubCardTop"><div><h3>'+esc(e.company)+'</h3><div class="hubCompany">'+esc(e.location||"Location not set")+'</div></div><span class="hubStatus">'+esc(e.status||"PROSPECT")+'</span></div><div class="hubMeta"><span>'+esc(e.contactName||"Contact not set")+'</span><span>'+esc(e.phone||"Phone n/a")+'</span><span>'+esc(e.email||"Email n/a")+'</span><span>WhatsApp: '+esc(e.whatsapp||"Unknown")+'</span><span>'+esc(e.source||"Local")+'</span></div><p class="hubReason">'+esc(e.notes||"")+'</p><div class="hubActions">'+(e.website?'<a href="'+esc(e.website)+'" target="_blank" rel="noopener">Website</a>':'')+'<button data-employer-detail="'+esc(e.id)+'">Full record · '+history.length+' application(s)</button></div></article>'}).join(""):'<div class="empty">No employer records match.</div>'}
  function openApplicationRecord(id){const rows=applications(),application=rows.find(a=>a.id===id);if(!application)return;const job=jobs().find(j=>j.id===application.jobId)||{role:"Job record",company:"Employer",location:""};const cv=currentCv();const history=(application.history||[]).slice().reverse();openSheet("Application record",'<form id="applicationRecordForm" class="hubForm"><div class="detail"><div class="detailRow"><span>Role</span><strong>'+esc(job.role)+'</strong></div><div class="detailRow"><span>Employer</span><strong>'+esc(job.company)+'</strong></div><div class="detailRow"><span>Location</span><strong>'+esc(job.location||"Not set")+'</strong></div><div class="detailRow"><span>Selected CV</span><strong>'+(cv?esc(cv.name)+' · Documents reference':'No CV · Add CV in Documents')+'</strong></div></div><label><span>Status</span><select name="status">'+statusOptions(application.status)+'</select></label><label><span>Next action</span><input name="nextAction" value="'+esc(application.nextAction||"")+'" placeholder="e.g. Call recruiter"></label><label><span>Follow-up date</span><input name="followUp" type="date" value="'+esc(application.followUp||"")+'"></label><button class="hubPrimary" type="submit">Save application record</button></form><div class="detail"><h3>Application history</h3>'+(history.length?history.map(h=>'<div class="detailRow"><span>'+esc(new Date(h.at).toLocaleString("en-GB"))+'</span><strong>'+esc(h.status)+' · '+esc(h.source||"local update")+'</strong></div>').join(""):'<p class="localOnly">No history recorded.</p>')+'</div>');q("#applicationRecordForm").addEventListener("submit",event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.target)),previous=application.status;application.status=form.status;application.nextAction=form.nextAction;application.followUp=form.followUp;application.updatedAt=new Date().toISOString();application.history=application.history||[];if(previous!==form.status)application.history.push({status:form.status,at:application.updatedAt,source:"explicit-user-update"});write(APPS_KEY,rows);closeSheet();renderApplications();renderJobs();showWorkToast("Application record updated locally.")})}
  function openEmployerRecord(id){const employer=employers().find(e=>e.id===id);if(!employer)return;const allJobs=jobs(),history=applications().map(a=>({application:a,job:allJobs.find(j=>j.id===a.jobId)})).filter(row=>row.job?.company===employer.company);openSheet("Employer / agency record",'<div class="detail">'+[["Company",employer.company],["Location",employer.location],["Contact",employer.contactName],["Phone",employer.phone],["Email",employer.email],["WhatsApp",employer.whatsapp],["Website",employer.website],["Source",employer.source],["Current status",employer.status],["Notes",employer.notes]].map(([key,value])=>'<div class="detailRow"><span>'+esc(key)+'</span><strong>'+esc(value||"Not set")+'</strong></div>').join("")+'<h3>Application history</h3>'+(history.length?history.map(row=>'<div class="detailRow"><span>'+esc(row.job.role)+'</span><strong>'+esc(row.application.status)+' · '+esc(row.application.followUp||"No follow-up")+'</strong></div>').join(""):'<p class="localOnly">No applications recorded for this employer.</p>')+'</div>')}
  function bindRecordActions(){document.addEventListener("click",event=>{const app=event.target.closest?.("[data-app-detail]");if(app)openApplicationRecord(app.dataset.appDetail);const employer=event.target.closest?.("[data-employer-detail]");if(employer)openEmployerRecord(employer.dataset.employerDetail)})}
  function addJob(){openSheet("Add construction job",'<form id="addJobForm" class="hubForm"><label><span>Construction trade</span><select name="trade" required>'+CONSTRUCTION_TRADES.map(x=>'<option>'+esc(x)+'</option>').join("")+'</select></label><label><span>Role</span><input name="role" required placeholder="e.g. Second Fix Joiner"></label><label><span>Company / agency</span><input name="company" required></label><label><span>Location</span><input name="location" required></label><label><span>Distance / travel time</span><input name="distance" placeholder="e.g. 8 mi · 25 min"></label><label><span>Rate</span><input name="rate"></label><label><span>Hours / shifts</span><input name="hours"></label><label><span>Employment type</span><input name="employmentType" placeholder="CIS / PAYE / Contract"></label><label><span>Required tickets</span><input name="requiredTickets" placeholder="CSCS, ECS, CPCS, SSSTS..."></label><label><span>Recruiter phone</span><input name="phone" type="tel"></label><label><span>Recruiter email</span><input name="email" type="email"></label><label><span>Original source URL</span><input name="sourceUrl" type="url"></label><button class="hubPrimary" type="submit">Save construction job</button></form>');q("#addJobForm").addEventListener("submit",e=>{e.preventDefault();const row=Object.fromEntries(new FormData(e.target));row.id="local-job-"+Date.now();row.status="NEW";row.source="Added manually · CONSTRUCTION ONLY · LOCAL";row.localDemo=true;row.constructionOnly=true;row.whatsapp=!!row.phone;const list=read(JOBS_KEY);list.unshift(row);write(JOBS_KEY,list);closeSheet();renderJobs()})}
  function addEmployer(){openSheet("Add employer / agency",'<form id="addEmployerForm" class="hubForm"><label><span>Company</span><input name="company" required></label><label><span>Location</span><input name="location"></label><label><span>Contact name</span><input name="contactName"></label><label><span>Phone</span><input name="phone" type="tel"></label><label><span>Email</span><input name="email" type="email"></label><label><span>WhatsApp</span><select name="whatsapp"><option>Unknown</option><option>Known</option><option>Not available</option></select></label><label><span>Website</span><input name="website" type="url"></label><label><span>Notes</span><textarea name="notes"></textarea></label><button class="hubPrimary" type="submit">Save locally</button></form>');q("#addEmployerForm").addEventListener("submit",e=>{e.preventDefault();const row=Object.fromEntries(new FormData(e.target));row.id="local-employer-"+Date.now();row.source="Added manually · LOCAL";row.status="PROSPECT";const list=read(EMPLOYERS_KEY);list.unshift(row);write(EMPLOYERS_KEY,list);closeSheet();renderEmployers()})}
  async function runWorkAgent(){
    const profile=window.NEXUS_WORK_PROFILE,gateway=profile?.jobGateway;if(!gateway?.endpoint){renderJobs();showWorkToast("Matches recalculated locally from the canonical Work Profile.");return}
    const prefs=profile.preferences||{},params=new URLSearchParams({what:prefs.targetRoles?.[0]||prefs.primaryTrade||"",where:prefs.locations?.[0]||"",country:gateway.queryDefaults?.country||"gb",results:String(gateway.queryDefaults?.results||10)});
    const button=q("#runWorkAgent");if(button)button.disabled=true;showWorkToast("NOSMO Work Agent is checking the Job Gateway...");
    try{const response=await fetch(gateway.endpoint+"?"+params);if(!response.ok)throw new Error("GATEWAY_UNAVAILABLE");const payload=await response.json();const rows=(payload.jobs||payload.results||[]).filter(isConstructionJob);profile.jobMatches=rows.map(normalizeJob);window.NOSMO_WORK_PROFILE_BRIDGE?.saveProfile?.();renderJobs();showWorkToast(rows.length+" construction job(s) loaded through "+(gateway.provider||"Job Gateway")+".")}
    catch(_){showWorkToast("Job Gateway is unavailable. Existing canonical/local records remain visible; no live search was claimed.")}
    finally{if(button)button.disabled=false}
  }
  function restoreSearchState(){try{const s=JSON.parse(localStorage.getItem("nosmo-work:v1:job-search")||"{}");[["jobSearchInput","input"],["jobStatusFilter","change"],["constructionTradeFilter","change"]].forEach(([id,type])=>{const el=q("#"+id);if(el&&s[id]!=null)el.value=s[id]})}catch(_){}}
  function bind(){restoreSearchState();STATUSES.forEach(s=>q("#jobStatusFilter")?.insertAdjacentHTML("beforeend",'<option>'+s+'</option>'));CONSTRUCTION_TRADES.forEach(s=>q("#constructionTradeFilter")?.insertAdjacentHTML("beforeend",'<option>'+s+'</option>'));qa("[data-hub-tab]").forEach(b=>b.addEventListener("click",()=>setTab(b.dataset.hubTab)));q("#jobSearchInput")?.addEventListener("input",renderJobs);q("#jobStatusFilter")?.addEventListener("change",renderJobs);q("#constructionTradeFilter")?.addEventListener("change",renderJobs);q("#employerSearchInput")?.addEventListener("input",renderEmployers);q("#runWorkAgent")?.addEventListener("click",runWorkAgent);q("#addJobButton")?.addEventListener("click",addJob);q("#addEmployerButton")?.addEventListener("click",addEmployer);q("#closeWorkHubSheet")?.addEventListener("click",closeSheet);q("#workHubBackdrop")?.addEventListener("click",e=>{if(e.target.id==="workHubBackdrop")closeSheet()});document.addEventListener("click",e=>{const prep=e.target.closest?.("[data-prepare]");if(prep){const j=jobs().find(x=>x.id===prep.dataset.prepare);if(j)prepare(j)}const detail=e.target.closest?.("[data-job-detail]");if(detail){const j=jobs().find(x=>x.id===detail.dataset.jobDetail);if(j)openSheet("Job record",'<div class="detail">'+Object.entries(j).filter(([k])=>!["id","localDemo"].includes(k)).map(([k,v])=>'<div class="detailRow"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join("")+'</div>')}});bindRecordActions();window.addEventListener("nexus:work-profile-ready",()=>{context();renderJobs();renderEmployers();if(typeof renderWork==="function")renderWork()});context();renderJobs();if(typeof renderWork==="function")renderWork()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
